FROM node:18-alpine
# setting build arguments for github actions
ARG NODE_ENV
ARG API_PORT
ARG API_HOST
ARG BASE_API_ROUTE
ARG REDIS_URL
ARG MONGO_URL
ARG HASHING_ALGORITHM
ARG ACCESS_TOKEN_SECRET
ARG ACCESS_TOKEN_EXPIRY_TIME
ARG REFRESH_TOKEN_SECRET
ARG REFRESH_TOKEN_EXPIRY_TIME
ARG VERIFY_TOKEN_SECRET
ARG VERIFY_TOKEN_EXPIRY_TIME
ARG CHANGE_PASSWORD_TOKEN_SECRET
ARG CHANGE_PASSWORD_TOKEN_EXPIRY_TIME
ARG PUBLIC_KEY
ARG PRIVATE_KEY
# setting env files form build arguments for github actions
ENV NODE_ENV=$NODE_ENV
ENV API_PORT=$API_PORT
ENV API_HOST=$API_HOST
ENV BASE_API_ROUTE=$BASE_API_ROUTE
ENV REDIS_URL=$REDIS_URL
ENV MONGO_URL=$MONGO_URL
ENV HASHING_ALGORITHM=$HASHING_ALGORITHM
ENV ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET
ENV ACCESS_TOKEN_EXPIRY_TIME=$ACCESS_TOKEN_EXPIRY_TIME
ENV REFRESH_TOKEN_SECRET=$REFRESH_TOKEN_SECRET
ENV REFRESH_TOKEN_EXPIRY_TIME=$REFRESH_TOKEN_EXPIRY_TIME
ENV VERIFY_TOKEN_SECRET=$VERIFY_TOKEN_SECRET
ENV VERIFY_TOKEN_EXPIRY_TIME=$VERIFY_TOKEN_EXPIRY_TIME
ENV CHANGE_PASSWORD_TOKEN_SECRET=$CHANGE_PASSWORD_TOKEN_SECRET
ENV CHANGE_PASSWORD_TOKEN_EXPIRY_TIME=$CHANGE_PASSWORD_TOKEN_EXPIRY_TIME
ENV PUBLIC_KEY=$PUBLIC_KEY
ENV PRIVATE_KEY=$PRIVATE_KEY
# where will be the project files will be listed inside the dontainer
WORKDIR /app
# copy the package.json and package-lock.json first to the workdir
COPY package.json package-lock.json ./
# run npm clean install to install all the dependencies first
RUN npm ci
# then copy all the project files to the workdir except the files listed in .dockerignore
COPY . .
# run the logFile.generator.js file to generate the logfile inside the workdir
RUN node /app/src/v1/generators/logFile.generator.js
# run the npm start command to start the server
CMD npm start
# expose the 3030 port
EXPOSE 3030